-- *** SECTION 1: SYSTEM ADMINISTRATION (OBJECT CREATION) ***

-- Switch to SYSADMIN to create the database object.
-- By default, SYSADMIN (the role used to execute the command) will own the database.
USE ROLE SYSADMIN;

-- 1. CREATE THE DATABASE
CREATE DATABASE IF NOT EXISTS SNOWPRO_COF_C02;

-- 2. CREATE THE WAREHOUSE
CREATE WAREHOUSE IF NOT EXISTS WAREHOUSE_1
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
;

-- *** SECTION 2: SYSTEM AND SECURITY ADMINISTRATION ***

-- Switch to SECURITYADMIN to create and manage users/roles and perform grants.
-- The SECURITYADMIN role also has the MANAGE GRANTS privilege needed for GRANT OWNERSHIP.
USE ROLE SECURITYADMIN;

-- 1. CREATE CUSTOM ROLE
CREATE ROLE IF NOT EXISTS ROLE_1;

-- 2. CREATE NEW USER
-- *** WARNING ***
-- THIS PASSWORD IS A TEMPORARY PLACEHOLDER AND MUST BE CHANGED IMMEDIATELY AFTER USER CREATION!
CREATE USER IF NOT EXISTS USER_1
  PASSWORD = 'TEMP_CHANGE_ME_NOW_123!' -- Placeholder for visibility
  DEFAULT_ROLE = ROLE_1
  DEFAULT_WAREHOUSE = WAREHOUSE_1
  MUST_CHANGE_PASSWORD = TRUE -- This line is CRITICAL for security
;

-- 3. TRANSFER OWNERSHIP OF THE DATABASE TO ROLE_1
GRANT OWNERSHIP ON DATABASE SNOWPRO_COF_C02 TO ROLE ROLE_1;

-- 4. GRANT WAREHOUSE USAGE TO ROLE_1
GRANT USAGE ON WAREHOUSE WAREHOUSE_1 TO ROLE ROLE_1;

-- 5. GRANT THE CUSTOM ROLE TO THE USER
GRANT ROLE ROLE_1 TO USER USER_1;

-- 6. CHECK GRANTS
SHOW GRANTS TO USER USER_1;
SHOW GRANTS TO ROLE ROLE_1;
